[supervisord]
nodaemon=true

[program:xvnc]
command=/usr/bin/Xvnc :1 -geometry 1280x1024 -depth 24 -rfbauth /root/.vnc/passwd -localhost -SecurityTypes VncAuth
autorestart=true

[program:xstartup]
command=/bin/sh -c "DISPLAY=:1 startxfce4"
autorestart=true

[program:websockify]
command=/opt/venv/bin/websockify --web=/opt/novnc 6080 localhost:5901
autorestart=true
